// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mftpggyqgzznbjkycebb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mdHBnZ3lxZ3p6bmJqa3ljZWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjE3ODEsImV4cCI6MjA3NDM5Nzc4MX0.6YDRZoTGQXipLuFGnuEEPx5sGarXqUDyXygjvDJfdFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});